import { Inter } from "next/font/google";
import './globals.css'
import RealTime from "./components/realtime";
import Link from "next/link"
import RealTimeIssue from "./components/realtimeissuse";
import Search_box from "./components/search_box";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



const RootLayout=({children})=>{
return (
    <html lang="en">
      <body className={inter.className}>
      <div className="navbar">
    <Link href="/">나무위키</Link>
    <Link href="/pages/changed">최근변경</Link>
    <Link href="/pages/arg">최근토론</Link>
    <a>특수기능</a>
     <button className="randomBtn">⟳</button>
   
     <Search_box/>
     </div>
 
   <div className="flex h-screen justify-center items-center">   
     <div className="flex content-center justify-center items-center border-[2px] text-[24px] w-70p h-95p ">
     <div className="w-full h-full  bg-white border-[2px] border-solid border-slate-500  mr-[20px] rounded-1p">
          <div className="w-full h-full">

          {children}
        


          </div>
         
      </div>
       <div className="flex justify-center items-center flex-col border-[2px] border-solid border-slate-500 bg-white rounded-3p w-30p h-full">
         <RealTime/>
         <RealTimeIssue/>
       </div>
    
     </div>
   </div>
         </body>
     </html>
   );

  




}

export default RootLayout


// <input className="search" placeholder="   여기에서 검색"></input>



//bg-green-500 justify-between relative p-[5px] pl-[300px] font-black
//justifty-center rounded-10p border-green-500 bg-white w-[45px] h-[45px] ml-[450px]
//

/*
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
        <Link href="/">나무위키</Link>
        <Link href="/pages/changed">최근변경</Link>
        <Link href="/pages/arg">최근토론</Link>
        <a>특수기능</a>
        { <ul className="hide">
          <ui>q</ui>
          <ui>q</ui>
          <ui>q</ui>
          <ui>q</ui>
        </ul>
         
         <button className="randomBtn">⟳</button>
         <input className="search" placeholder="   여기에서 검색"></input>
         </div>
 
         {children}</body>
     </html>



*/ 

/*
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="navbar">
    <Link href="/">나무위키</Link>
    <Link href="/pages/changed">최근변경</Link>
    <Link href="/pages/arg">최근토론</Link>
    <a>특수기능</a>
    { <ul className="hide">
      <ui>q</ui>
      <ui>q</ui>
      <ui>q</ui>
      <ui>q</ui>
    </ul>
     }
     <button className="randomBtn">⟳</button>
     <input className="search" placeholder="   여기에서 검색"></input>
     </div>
 
   <div className="flex h-screen justify-center items-center">   
     <div className="flex content-center justify-center items-center border-[2px] text-[24px] w-70p h-95p ">
       <div className="flex w-full h-full bg-white border-[2px] border-solid border-slate-500 justify-center mr-[20px] rounded-1p">
       {children}
       </div>
       <div className="flex justify-center items-center  border-[2px] border-solid border-slate-500 bg-white rounded-3p w-30p h-full">
         <RealTime/>
       </div>
    
     </div>
   </div>
         </body>
     </html>
   );
 } */